import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          <div className="m-auto px-6 py-4 align-center gap-4 space-y-4 w-[85%]">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
